[autoconf]
git-tree-sha1 = "42a41d2cb8f2827f7d879cc8b749238f56a10cd4"

    [[autoconf.download]]
    sha256 = "a39d8e6c6a26cfbb25d484c8ac63d6c652499bbbdf82d3795957d653ad300aa2"
    url = "https://github.com/JuliaBinaryWrappers/autoconf_jll.jl/releases/download/autoconf-v2.72.0+1/autoconf.v2.72.0.any.tar.gz"
